[package]
name = "a"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
b.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
